### ISSUE TITLE
"Lost Connection to Sabnzbd"

### ISSUE THREAD

**Issue by labrys** [sabnzbd/sabnzbd#1059]
Lost connection to sab for an extended period.   It looks like it was during deletion of a failed download (Approx 6gb expected size).   Took Approx 10 minutes to finish the deletion.  During this time the downloader crashed and restarted itself.

**Comment by Safihre** [comment]
Do you have logging set to Debug? The new extra logging that was added to resolve the Import errors is slower, and thus takes much longer. Although 10min is not normal of course. 

So what errors are in te log?

**Comment by Safihre** [comment]
Pushed a new commit that greatly decreases the performance impact of `+Debug` logging, it should now almost have no impact at all any more.

**Comment by labrys** [comment]
Yes debug logging is enabled.  This was on the latest commit.  Other than the error about the downloader crashing and restarting there were no other errors.  The downloader crashing happened about two minutes into the deletion process so I think it may have crashed due to the process taking too long.  After the UI became responsive again, I did a shutdown and went to the logs to post them, but the logs were not updated.  The last timestamp in the logs was from the previous day.  I deleted the previous logs and started sab back up and the logs are currently updating.

**Comment by Safihre** [comment]
I'd suggest a `git pull`, hopefully it resolves the issue! Let me know if it doesn't.

**Comment by Safihre** [comment]
@labrys Any more problems?

**Comment by labrys** [comment]
I still get lost connection to SAB when the downloader crashes (to be expected while the service restarts), but the duration is significantly shorter.  I would say this is solved for the original issue.

**Comment by Safihre** [comment]
But why does the downloader crash? Any indication in the logs?

**Comment by labrys** [comment]
Its related to the import error, the exception about nzf file has no attribute.

**Comment by Safihre** [comment]
Ah yes, but that has been fixed 2 weeks ago: https://github.com/sabnzbd/sabnzbd/commit/39cceed5805f675cb3b45a7c93773c45abe6be1b 👍

**Comment by labrys** [comment]
I don't think I have had any errors with the urlgrabber crashing since the last time I updated, at least there's none in my logs.  I do still have the Error importing though, unfortunately by the time I notice the error the NZF file information is usually no longer in the logs.  This issue should be closed though.

**Comment by Safihre** [comment]
Ok!
