### ISSUE TITLE
Files leftover in /completed

### ISSUE THREAD

**Issue by cphmichael** [sabnzbd/sabnzbd#1630]
SABnzbd Version: 3.2.0-develop [unknown]
Python Version: 3.8.5 (default, Jul 20 2020, 23:11:29) [GCC 9.3.0] [UTF-8]
OpenSSL: OpenSSL 1.1.1g 21 Apr 2020

Sonarr Version: 3.0.3.938
Package Version: nightly-b46422a-156 by hotio
Mono Version: 6.10.0.104

Every time Sonarr/SABnzbd has processed a download - The original file is still in /completed.

Every thing works as expected - Then only problem is, that I manually have to delete the folder/files from /completed.
And if I receive a lot of big-size files, my cache ssd drive runs full.

![image](https://user-images.githubusercontent.com/45288008/95296433-0f8e9680-0879-11eb-86b2-643046846a20.png)

![image](https://user-images.githubusercontent.com/45288008/95296452-174e3b00-0879-11eb-9924-12017355d949.png)

I have created a ticket for that in the Sonarr forum with debug files etc:

https://forums.sonarr.tv/t/file-leftover-in-completed/26664

The answer from Markus is:

- - - - - 

`
20-10-5 12:36:43.1|Debug|DiskScanService|2 video files were found in /downloads/completed/Series/Fargo.S04E03.Raddoppiarlo.1080p.AMZN.WEB-DL.DDP5.1.H.264-TOMMY84506tMbYC(1).mkv
Fargo.S04E03.Raddoppiarlo.1080p.AMZN.WEB-DL.DDP5.1.H.264-TOMMY.mkv
`

Ultimately Sonarr imported the first file (looks like it was obfuscated):

`
20-10-5 12:36:43.3|Debug|EpisodeFileMovingService|Moving episode file: /downloads/completed/Series/Fargo.S04E03.Raddoppiarlo.1080p.AMZN.WEB-DL.DDP5.1.H.264-TOMMY/84506tMbYC(1).mkv to /tv/Fargo/Season 04/Fargo - S04E03 - Raddoppiarlo [WEBDL-1080p] [h264 EAC3]-TOMMY.mkv
`

Sonarr then won’t import the second because it’s already imported that episode and it won’t delete the folder because there is a valid video file in there.

For some reason SAB has put two files in there, perhaps due to some de-obfuscation? That’s not something Sonarr expect nor will deal with, you’ll need to troubleshoot on the SAB side to figure out what’s going on.

**Comment by sanderjo** [comment]
> perhaps due to some de-obfuscation?

Do you have de-obfuscation turned in SABnzbd on? Check http://127.0.0.1:8080/sabnzbd/config/switches/#deobfuscate_final_filenames . If not, just keep it off, but it is also the proof that deob is not involved.

Can you make clear which files are there after the download by SAB, so before Sonarr starts working? Because I did a download with the same name, and it only gives one MKV.

**Comment by Safihre** [comment]
@sanderjo This is not related to your feature, but related to something not working well with Direct Unpack.

@cphmichael Could you enable +Debug logging in the Status Window, then after it happens again click Show Logging in the same window.
Could you share the full logs here (through pastebin) or email them at safihre@sabnzbd.org?
Also: what commit are you on?

**Comment by cphmichael** [comment]
The 'Deobfuscate final filenames' was ticked.

I have uploaded the debug log to Google Drive - I hope that is okay because I think it is to big for pastbin:

https://drive.google.com/file/d/1Tf_Z067ti44gf8wOQQThYP3SODXMg2_c/view?usp=sharing

![image](https://user-images.githubusercontent.com/45288008/95314607-ceef4700-0891-11eb-90a0-3d2feab259ee.png)

![image](https://user-images.githubusercontent.com/45288008/95314703-e8908e80-0891-11eb-9759-773311d39882.png)

**Comment by Cpuroast** [comment]
For the time being, turn off "Switches, Queue, Direct Unpack", and it should resolve the issue.

I've seen Sab not realize that direct unpack succeeded and proceeds with a traditional post-processing unpack when the download completes resulting in a duplicate.

**Comment by cphmichael** [comment]
I will turn off ‘Direct Unpack’ and hope that resolve the issue.

Thank you for your advice.

**Comment by Safihre** [comment]
I want to fix these cases of course..

**Comment by Safihre** [comment]
It turned out that in a recent commit I broke Direct Unpack.
Fixed it now.

If you want a more stable experience, I would suggest to use the `master` branch. It always has the latest stable release.
But if you don't mind sometimes things being broken, it helps a lot if you keep reporting them! 💯 🎖️

**Comment by cphmichael** [comment]
I have changed from: SABnzbd Version "3.2.0-develop" to "**3.1.0RC3**" but I still see leftover files in /completed.

[sabnzbd.log](https://github.com/sabnzbd/sabnzbd/files/5390145/sabnzbd.log)

![image](https://user-images.githubusercontent.com/45288008/96232547-4ca10a00-0f98-11eb-8d54-9ed4b636932a.png)

![image](https://user-images.githubusercontent.com/45288008/96233242-7ce8a880-0f98-11eb-83bd-f8c07394afaa.png)
