### ISSUE TITLE
1.1.0RC2: Can't login from mobile Chrome Browser

### ISSUE THREAD

**Issue by LoveBootCaptain** [sabnzbd/sabnzbd#601]
I can't login to WebInterface from mobile Browser.
filled in username / password and hit login, but nothing happened.
I tried to delete saved password from chrome but still no success.
I tried new username/password in sabnzbd settings (from other device) but still no success.

Browser Version: Android Chrome 51.0.2704.81
Device: Nexus 5X
OS: Android 6.0.1 / June (Stock)
SABnzbd-Version: 1.1.0Beta1 Skin: Glitter

**Comment by Safihre** [comment]
Did you possible disable cookies or some other privacy settings?

**Comment by LoveBootCaptain** [comment]
Nope... Before i updated to latest version it worked perfectly

**Comment by Safihre** [comment]
Strange, I can't reproduce it. For now the fix would be to go into Config > Specials and disable ```html_form```.

**Comment by LoveBootCaptain** [comment]
Got it working after deleting all app related data and re-sign-in to Google
chrome... strange, that never happens before.
Am 18.06.2016 5:10 nachm. schrieb "Safihre" <notifications@github.com>:

**Comment by Safihre** [comment]
Are you running other services from this IP/domain? Like couchpotato or sonarr? It could be that the maximum number/length of cookies was reached.

**Comment by Safihre** [comment]
Fixed, close?

**Comment by LoveBootCaptain** [comment]
Nope... Still having that problem. Delete all App data helps just for one
login. After that login is impossible again on chrome for Android.

Am 19.07.2016 7:23 nachm. schrieb "Safihre" <notifications@github.com>:

**Comment by Safihre** [comment]
How about my previous question what other services are running on that domain?

**Comment by LoveBootCaptain** [comment]
Damn... Forgot to answer that.
Yes... It's a dyn DNS domain and I use some web based services.

But when I'm in local network there are only 2 webservices running on that
IP that needs login (sabnzbd and sickbeard) .

I remember chrome changed some stuff with username password function. That
breaks saved passwords on some websites.

Regards

Am 19.07.2016 8:26 nachm. schrieb "Safihre" <notifications@github.com>:

**Comment by Safihre** [comment]
Thanks! Will investigate.
One more (maybe irrelevant) question: does your username or password contain any special German characters like umlauts etc?

**Comment by LoveBootCaptain** [comment]
Nope... Just some random numbers and letters. No umlauts, no special
characters

Am 19.07.2016 9:05 nachm. schrieb "Safihre" <notifications@github.com>:

**Comment by LoveBootCaptain** [comment]
Short Update... Problem is still reproducible with latest RC. :(

**Comment by thezoggy** [comment]
are you using the web form login or the popup?
try toggling the config option to do the alt method.. 
`config > special > html_login`

**Comment by Safihre** [comment]
The webform should also work.. I can't reproduce it or think of a reason why it should misbehave, besides too many cookies on the domain or some other cookie-altering layer.
@sanderjo  did you ever experience with login problems with the new login behind your proxy?

**Comment by LoveBootCaptain** [comment]
when i toggle to old login, everything is fine and i can login.
the html login works, when i`m in my local network and when i use the IP address to oben sabnzbd.
when i use the dyn-dns url i can't login.
i tried to delete all cookies in that android chrome browser, but it had no effect. still no login.
i checked also chrome for iOS... here is everything fine... both login methods works perfect.
seems to be an android only problem... at lest for me.
hope that information will help. regards

**Comment by sanderjo** [comment]
> @sanderjo did you ever experience with login problems with the new login behind your proxy?

No, no problems with Mobile Chrome (Chrome/51.0.2704.81 Mobile) and SAB 1.1.0RC2 (the PPA version)

**Comment by LoveBootCaptain** [comment]
The problem magically disappeared after updating my Nexus 5X to Android 7.0.
Strange thing cause I didn't make a factory reset. I just installed the OTA... Chrome Version is still the same.
If nobody else had this problem this could be closed I guess

**Comment by cjgreen** [comment]
I had been experiencing this issue for a while, I just figured out that disabling Data Saver in Chrome Settings resolved the issue for me.

**Comment by Safihre** [comment]
@cjgreen Thanks! Good to know.

**Comment by mudsloth** [comment]
Just wanted to say that I experienced this same issue and it was solved by disabling data saver.
