### ISSUE TITLE
previous tab that shut down sab with, will kill new sab instance when loaded

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#612]
i'll shut down sab via the webui then kill browser and reboot machine. startup sab on boot/etc..  then load up browser later on. if i click on that old sab session tab.. sab gets killed... this shouldnt happen. we should add something to the url (optional) that keeps it unique to the point that if it is refreshed the action isnt called/affects future sab instances..    in sb we used to do `?pid=###` so that the calls was for only THAT instance

**Comment by Safihre** [comment]
Sounds good, only side-note would be that this is sort of a breaking API-change since tools that rely on the ```shutdown``` command don't know that they need to send the ```pid``` (which is send in the ```queue``` command).

**Comment by shypike** [comment]
The interface code checks for session-key, if that's absent it will check for an API-key.
We could post-prefix just the session-key with the PID.
The API-key wouldn't need it.
It's not a security fix, but a mistake-prevention fix.

Having said that, I find it very convenient that I can use an open Web-UI on a new instance of the SABnzbd code. That would no longer work.
We could be adding confusion instead of lessening it.

**Comment by thezoggy** [comment]
maybe a better fix is to tackle what sab does when it shuts down.... add a javascript redirect or something to the shutdown page so that it re-directs to a non shutdown url after a few seconds.... like a generic sab page stating that sab is shutting down / sab help page/donation

**Comment by Safihre** [comment]
I have been looking into this, and I seem unable to get CherryPy to stream the output.
Even though we use ```yield```, adding the ```stream: true``` to the function it outputs only when it's done shutting down. So can't redirect to another page anymore.

Suggestion: 
Make skin shutdown-links add ```&pid=xx```, if a ```pid``` is present it will only shutdown if it's the right ```pid```. 
If no ```pid``` is present in the URL, then still shutdown so API compatibility is kept?

**Comment by shypike** [comment]
@Safihre  Sounds OK

**Comment by thezoggy** [comment]
also to note, in sb we would check the pid and see if the pid passed isnt the pid of the current instance.. if so we redirected them to the home screen..

https://github.com/midgetspy/Sick-Beard/blob/development/sickbeard/webserve.py#L2167

thus if this was implemented then refreshing on that previous shutdown tab, would just take me to the home screen.

**Comment by Safihre** [comment]
Fixed, close?

**Comment by thezoggy** [comment]
still an issue :(
just shutdown 1.1.0RC1, installed RC2 and started it up. then on my RC1 shutdown tab ( `http://ip:port/sabnzbd/shutdown/?session=<removed>` ).. hit refresh.. then it showed:
```
Initiating shutdown...
SABnzbd-1.1.0RC2 shutdown finished
```

**Comment by shypike** [comment]
Obviously RC1 will shutdown when exposed to the URL. What is solved is that an old RC2 session URL doesn't terminate new RC2 session. It was never the intention to fix it retrospectively for RC1.
